### ISSUE TITLE
Bug: Adding a pipeline command after `show` results in a stack trace error

### ISSUE THREAD

**Issue by theomega** [abey79/vpype#176]
How to reproduce:

```
$ vpype read LabradorLowPoly.svg show stat
========= Stats ========= 
Traceback (most recent call last):
  File "/home/dominik/.local/bin/vpype", line 8, in <module>
    sys.exit(cli())
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype_cli/cli.py", line 74, in main
    return super().main(args=preprocess_argument_list(args), **extra)
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype_cli/cli.py", line 128, in process_pipeline
    execute_processors(processors)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype_cli/cli.py", line 212, in execute_processors
    state = proc(state)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype/decorators.py", line 150, in global_processor
    state.document = f(state.document, *args, **kwargs)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype_cli/debug.py", line 135, in stat
    print(f"Current page size: {document.page_size}")
AttributeError: 'NoneType' object has no attribute 'page_size'
```

Also true with the classic show:
```
$ vpype read LabradorLowPoly.svg show --classic stat
========= Stats ========= 
Traceback (most recent call last):
  File "/home/dominik/.local/bin/vpype", line 8, in <module>
    sys.exit(cli())
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype_cli/cli.py", line 74, in main
    return super().main(args=preprocess_argument_list(args), **extra)
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/home/dominik/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype_cli/cli.py", line 128, in process_pipeline
    execute_processors(processors)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype_cli/cli.py", line 212, in execute_processors
    state = proc(state)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype/decorators.py", line 150, in global_processor
    state.document = f(state.document, *args, **kwargs)
  File "/home/dominik/.local/lib/python3.8/site-packages/vpype_cli/debug.py", line 135, in stat
    print(f"Current page size: {document.page_size}")
AttributeError: 'NoneType' object has no attribute 'page_size'
```

Version:
```
$ vpype --version
vpype 1.3.0a0
```

**Comment by abey79** [comment]
bug introduced in #163
